version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/installDocker
      timeout: 600
      runas: root
  AfterInstall:
    - location: scripts/updateImage
      timeout: 600
      runas: root
